services:

  react-ui:
    image: node:16-alpine
    working_dir: /opt/react_app
    command: npm start
    ports:
      - "80:3000"
    stdin_open: true
    volumes:
      - .:/opt/react_app
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
      - PATH=/opt/react_app/node_modules/.bin:$PATH